### ISSUE TITLE
Permission issues to access the .statuses folder

### ISSUE THREAD

**Issue by StrangeCurious** [yatiksihag01/Status-Saver#2]
No proper permissions are asked once we open the app to access the .statuses folder and show all the statuses

**Comment by yatiksihag01** [comment]
Hi @StrangeCurious could you specify which specific permissions you believe are not being asked when accessing the ".statuses" folder and please mention the Android version you are using. Please add screenshots of the bug if you can.

**Comment by StrangeCurious** [comment]
I am using the latest android 13.

**Comment by StrangeCurious** [comment]
![WhatsApp Image 2023-08-10 at 01 40 07](https://github.com/yatiksihag01/Status-Saver/assets/125676698/bbd51ebd-2f17-4c15-ad3d-51058f71af6c)
![WhatsApp Image 2023-08-10 at 01 40 06 (1)](https://github.com/yatiksihag01/Status-Saver/assets/125676698/1bbdebde-b040-4393-9135-1754c41d5898)
This is what your app show. No permissions are required

**Comment by StrangeCurious** [comment]
![WhatsApp Image 2023-08-10 at 01 40 06](https://github.com/yatiksihag01/Status-Saver/assets/125676698/c4f37466-903f-4e0c-a73f-ca6e555d2848)
This is what actually it should ask for the permission

**Comment by yatiksihag01** [comment]
Hi @StrangeCurious can you please check if everything is working fine. Please also check for Android 9 or below if you can.

**Comment by StrangeCurious** [comment]
There are few things which I noticed.
-> The recyclerview in the saved fragment is not proper. There is unnecessory loading of there items in recycler view.
-> There is no delete option for saved images.
-> There is an other app called 'Leaks' which gets installed and if I uninstall leaks, your app also gets uninstall.
Thankyou for your response..

![WhatsApp Image 2023-08-12 at 10 30 51](https://github.com/yatiksihag01/Status-Saver/assets/125676698/e2783a32-852c-4c86-8b5d-da6da47ba13b)
![WhatsApp Image 2023-08-12 at 10 30 50](https://github.com/yatiksihag01/Status-Saver/assets/125676698/53c64eaa-bde7-4888-84d7-505fb279547c)

**Comment by yatiksihag01** [comment]
* These unnecessary loading icons sometimes appear if you paste/create any other directory inside `Downloads/StatusSaver` directory.
* Yes, currently there is no delete option. It's because I don't update this project frequently. But you can do it by checking which fragment set the adapter and set save icon and it's functionality according to that.
* That leaks app is from [Square](https://square.github.io/), you can read more about it [here](https://square.github.io/leakcanary/fundamentals/). This app is just with the debug version of app and not with release variant.

**Comment by StrangeCurious** [comment]
ok, Thankyou
