### ISSUE TITLE
READ_EXTERNAL_STORAGE is depricated when targenting android 13+.

### ISSUE THREAD

**Issue by StrangeCurious** [yatiksihag01/Status-Saver#4]
READ_EXTERNAL_STORAGE is deprecated (and is not granted) when targeting Android 13+. If you need to query or interact with MediaStore or media files on the shared storage, you should instead use one or more new storage permissions: `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` or `READ_MEDIA_AUDIO`.

This is the new issue for latest android 13

**Comment by yatiksihag01** [comment]
For android 10 and above, we are explicitly asking user for statuses folder permission and as per android official [documentation](https://developer.android.com/training/data-storage/shared/media#storage-permission-not-always-needed) "On devices that run Android 10 or higher, you don't need storage-related permissions to access and modify media files that your app owns, including files in the MediaStore.Downloads collection". That means we don't need `READ_EXTERNAL_STORAGE` permission at  all. Please elaborate what exactly the issue is.

**Comment by StrangeCurious** [comment]
That means it will work perfectly for all the devices of any android versions?
